# Generated by Django 2.2.1 on 2020-09-08 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время попытки входа')),
                ('ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='IP адрес')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='Юзер-агент')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Логин')),
                ('path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес авторизации')),
                ('result', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Авторизация в системе',
                'verbose_name_plural': 'Авторизации в системе',
            },
        ),
    ]
