# Generated by Django 2.2.1 on 2020-09-08 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.PositiveIntegerField(unique=True, verbose_name='ID пользователя')),
                ('gender', models.CharField(choices=[('male', 'М'), ('female', 'Ж')], max_length=6, verbose_name='Пол')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('phone_checked', models.BooleanField(default=False, verbose_name='Номер телефона подтвержден')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Электронная почта')),
                ('email_checked', models.BooleanField(default=False, verbose_name='Электронная почта подтверждена')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('password', models.CharField(max_length=500, verbose_name='Пароль')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house', models.CharField(max_length=255, verbose_name='Номер дома')),
                ('appartment', models.CharField(max_length=255, verbose_name='Номер квартиры')),
                ('index', models.CharField(max_length=255, verbose_name='Почтовый индекс')),
                ('add_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Последнее изменение')),
                ('birthday', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата рожденья')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Аккаунт Пользователя',
                'verbose_name_plural': 'Аккаунты Пользователей',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира / офис')),
                ('add_info', models.CharField(blank=True, max_length=250, null=True, verbose_name='Дополнительная информация')),
                ('selected', models.BooleanField(default=False)),
                ('delivery', jsonfield.fields.JSONField(blank=True, default='{}', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-selected', 'pk'],
            },
        ),
    ]
