# Generated by Django 2.2.1 on 2020-09-08 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_old', models.CharField(blank=True, choices=[('new', 'Новый заказ'), ('created', 'Создан, ожидает оплаты'), ('payed', 'Оплачен, в обработке'), ('prepered', 'Собран, ожидает передачи на доставку'), ('at_delivry', 'Передан на доставку'), ('delivring', 'Доставляется'), ('delivred', 'Доставлен'), ('declined', 'Отменен')], editable=False, max_length=255, null=True, verbose_name='Статус заказа')),
                ('status', models.CharField(choices=[('new', 'Новый заказ'), ('created', 'Создан, ожидает оплаты'), ('payed', 'Оплачен, в обработке'), ('prepered', 'Собран, ожидает передачи на доставку'), ('at_delivry', 'Передан на доставку'), ('delivring', 'Доставляется'), ('delivred', 'Доставлен'), ('declined', 'Отменен')], max_length=255, verbose_name='Статус заказа')),
                ('order_id', models.PositiveIntegerField(unique=True, verbose_name='Номер заказа')),
                ('products_cost', models.PositiveIntegerField(blank=True, default=0, verbose_name='Стоимость товаров')),
                ('discount_cost', models.PositiveIntegerField(blank=True, default=0, verbose_name='Скидка по купону')),
                ('delivery_cost', models.PositiveIntegerField(blank=True, default=0, verbose_name='Стоимость доставки')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Время заказа')),
                ('payed', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Время оплыта')),
                ('customer_name', models.CharField(max_length=500, verbose_name='Покупатель')),
                ('phone', models.CharField(max_length=24, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('adress', models.TextField(verbose_name='Адрес доставки')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Примечания к заказу')),
                ('delivery_type', models.CharField(max_length=24, verbose_name='Способ доставки')),
                ('track_number', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Трэк-номер')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Вес коробки')),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ширина коробки')),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Высота коробки')),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Длина коробки')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coupon.Coupon', verbose_name='Скидочный купон')),
                ('customer', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Список заказов',
                'verbose_name_plural': 'Список заказов',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=255, verbose_name='Артикул')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количесвто, шт')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена за шт')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.Color', verbose_name='Цвет')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.Order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.Product', verbose_name='Продукт')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.Variant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
