# Generated by Django 2.2.1 on 2020-09-08 15:06

import ckeditor.fields
import colorfield.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, editable=False, max_length=320, null=True, verbose_name='Иденитификатор')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Название категории')),
                ('in_catalogue', models.BooleanField(default=False, verbose_name='Показывать на витрине по умолчанию')),
                ('in_recomendation', models.BooleanField(default=False, verbose_name='Предлагать в рекомендованные')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('slug', models.CharField(blank=True, editable=False, max_length=320, null=True, verbose_name='Иденитификатор')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Название цвета')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото цвета')),
                ('image_thmb', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('hex', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, unique=True, verbose_name='Код цвета')),
            ],
            options={
                'verbose_name': 'Цвет товара',
                'verbose_name_plural': 'Цвета товаров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GiftReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, editable=False, max_length=320, null=True, verbose_name='Иденитификатор')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Повод для подарка',
                'verbose_name_plural': 'Повод для подарка',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=255, verbose_name='Артикул')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('old_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Прежняя цена')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер скидки')),
                ('in_sell', models.BooleanField(default=True, verbose_name='В продаже')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Карточка товара (основная)')),
                ('image_thmb', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('add_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Карточка товара (дополнительная)')),
                ('add_image_thmb', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('length', models.PositiveIntegerField(null=True, verbose_name='Длина (см)')),
                ('width', models.PositiveIntegerField(null=True, verbose_name='Ширина (см)')),
                ('height', models.PositiveIntegerField(null=True, verbose_name='Высота (см)')),
                ('weight', models.PositiveIntegerField(null=True, verbose_name='Вес (кг)')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('preferences', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Характеристики')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Последнее изменение')),
                ('category', models.ManyToManyField(blank=True, related_name='product', to='shop.Category', verbose_name='Категория товарв')),
                ('gift_reason', models.ManyToManyField(blank=True, related_name='product', to='shop.GiftReason', verbose_name='Повод для подарка')),
            ],
            options={
                'verbose_name': 'Список товаров',
                'verbose_name_plural': 'Список товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, editable=False, max_length=320, null=True, verbose_name='Иденитификатор')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Название')),
                ('hex', colorfield.fields.ColorField(default='#000000', max_length=18, verbose_name='Код цвета')),
            ],
            options={
                'verbose_name': 'Статус товара',
                'verbose_name_plural': 'Статус товара',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhoIntended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, editable=False, max_length=320, null=True, verbose_name='Иденитификатор')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Кому предназначен',
                'verbose_name_plural': 'Кому предназначен',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first', models.BooleanField(default=False)),
                ('photo_1', models.FileField(upload_to='', verbose_name='Фото 1')),
                ('photo_1_thmb', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('photo_2', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото 2')),
                ('photo_2_thmb', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('photo_3', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото 3')),
                ('photo_3_thmb', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('photo_4', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото 4')),
                ('photo_4_thmb', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('in_stock', models.PositiveIntegerField(default=1, verbose_name='В наличии')),
                ('hide', models.BooleanField(default=False)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='shop.Color', verbose_name='Цвет')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Цвет товара',
                'verbose_name_plural': 'Цвета товаров',
                'ordering': ['-first', 'color__name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ManyToManyField(blank=True, related_name='product', to='shop.ProductStatus', verbose_name='Статус товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='who_intended',
            field=models.ManyToManyField(blank=True, related_name='product', to='shop.WhoIntended', verbose_name='Кому предназначен'),
        ),
    ]
