# Generated by Django 2.2.1 on 2020-09-08 15:11

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Код цвета'),
        ),
    ]
