# Generated by Django 2.2.1 on 2020-09-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200908_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='product', to='shop.Category', verbose_name='Категория товаров'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Артикул'),
        ),
    ]
