# Generated by Django 2.2.1 on 2020-09-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200908_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Артикул'),
        ),
    ]
