# Generated by Django 2.2.1 on 2020-09-08 15:06

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название странциы')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Карточка товара (основная)')),
                ('image_thmb', jsonfield.fields.JSONField(blank=True, default='{}', editable=False, null=True)),
                ('menu_hide', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Страница магазина',
                'verbose_name_plural': 'Страницы магазина',
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название блока')),
                ('text', models.TextField(verbose_name='Текст блока')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='pages.Page')),
            ],
            options={
                'verbose_name': 'Информационный блок',
                'verbose_name_plural': 'Информационные блоки',
            },
        ),
    ]
