# Generated by Django 2.2.1 on 2020-09-08 15:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст блока'),
        ),
    ]
