# Generated by Django 2.2.1 on 2020-09-08 17:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200908_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Карточка товара (основная)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image_thmb',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
