# Generated by Django 2.2.1 on 2020-09-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveIntegerField(verbose_name='Сумма скидки')),
                ('unit', models.CharField(choices=[('percent', 'Проценты'), ('rub', 'Рубли')], max_length=255, verbose_name='Измерение')),
                ('minimum', models.PositiveIntegerField(verbose_name='Минимальная сумма заказа')),
                ('text', models.CharField(max_length=1000, verbose_name='Текст промокода')),
                ('expired', models.BooleanField(default=False, verbose_name='Срок действия закончился')),
                ('onece', models.BooleanField(default=False, verbose_name='Использовать только 1 раз')),
                ('used', models.BooleanField(default=False, verbose_name='Использован')),
            ],
        ),
    ]
